export const ARCHETYPES = {
  trail: {
    key: "trail",
    emoji: "🌟",
    name: "Sang Perintis",
    type: "Digital Startup Founder",
    power: "Eksekusi + baca peluang digital",
    glow: "#ff7a59",
    fortune:
      "Kamu tipe yang udah jalan sebelum yang lain selesai mikir.",
    prospek: "Global Entrepreneur • Entrepreneur • Digital Business Specialist",
    courses: ["Digital Innovation", "Launch Creative Business Startup", "Startup Funding"],
    dreamyMessage: "Impianmu seperti bintang berjatuhan - cepat, cerah, dan penuh peluang tak terduga. Percayalah pada instinct pertamamu, karena itulah petunjuk alam semesta menuju nasibmu.",
  },
  tech: {
    key: "tech",
    emoji: "⚡",
    name: "Sang Penerus",
    type: "Digital Business Successor",
    power: "Bawa usaha lama ke ranah digital",
    glow: "#5b8cff",
    fortune:
      "Kamu nggak harus mulai dari nol - keahlianmu bikin usaha yang udah ada jadi naik kelas.",
    prospek: "Business Developer • Digital Business Specialist • Small Business Consultant",
    courses: ["Enterprise Business Process", "Family Business", "Information Systems Management, Strategy and Acquisition"],
    dreamyMessage: "Impianmu seperti jembatan cahaya yang menghubungkan masa lalu dan masa depan. Kekuatanmu ada dalam menghormati akar sambil menuju ke innovations yang mengguncang dunia.",
  },
  create: {
    key: "create",
    emoji: "🎨",
    name: "Sang Kreator",
    type: "Digital Marketing Entrepreneur",
    power: "Branding + data buat dongkrak jualan",
    glow: "#ff5fa8",
    fortune:
      "Kamu jago bikin orang naksir sama sesuatu.",
    prospek: "Digital Business Specialist • Business Developer",
    courses: ["Marketing for Entrepreneur", "Data and Information Management", "Commercializing Emerging Technology"],
    dreamyMessage: "Impianmu seperti pelangi di langit senja - warna-warni, menarik perhatian, dan membuat orang berhenti untuk menatap. Kreativitasmu adalah panggilan jiwa yang harus kau ikuti.",
  },
  design: {
    key: "design",
    emoji: "💎",
    name: "Sang Inovator Produk",
    type: "Digital Product Innovator",
    power: "Rancang produk digital yang dicintai",
    glow: "#b06bff",
    fortune:
      "Kamu bikin produk yang bikin orang mikir 'kok enak banget ya dipake'. Produk yang doublenk jadi bisnis beneran.",
    prospek: "Entrepreneur • UX Designer • Digital Business Specialist",
    courses: ["User Experience Research and Design", "Digital Business Project", "Innovative Product Design and Development"],
    dreamyMessage: "Impianmu seperti kristal yang bersinar dalam gelam - jernih, indah, dan memiliki struktur yang sempurna. Perhatianmu pada detail adalah karunia yang akan mengubah cara orang berinteraksi dengan teknologi.",
  },
  change: {
    key: "change",
    emoji: "🌱",
    name: "Sang Pengubah",
    type: "Sustainable Digital Intrapreneur",
    power: "Bisnis berkelanjutan pakai teknologi",
    glow: "#2ecc8f",
    fortune:
      "Buat kamu, bisnis itu alat buat bikin perubahan.",
    prospek: "Intrapreneur • Small Business Consultant • Business Developer",
    courses: ["Sustainable Business Model", "Foundations of Artificial Intelligence", "Business Law and Ethics"],
    dreamyMessage: "Impianmu seperti benih yang tumbuh di tanah subur - perlahan namun pasti, membawa kehidupan dan manfaat bagi yang sekeliling. Kepedulianmu pada dampak adalah panggilan yang mulia di era digital ini.",
  },
  strat: {
    key: "strat",
    emoji: "🧭",
    name: "Sang Penyusun Strategi",
    type: "Digital Business Strategist",
    power: "Strategi & angka di balik startup",
    glow: "#ffb020",
    fortune:
      "Kamu lihat bisnis kayak papan catur.",
    prospek: "Business Planner • Business Analyst • Information System Consultant",
    courses: ["Business Plan", "Information Systems Project Management", "Entrepreneurial Finance and Accounting"],
    dreamyMessage: "Impianmu seperti peta bintang dalam malam yang gelap - memberikan arah, tujuan, dan jalan yang jelas. Kemampuanmu melihat pola dan pola adalah anugerah yang jarang ditemukan.",
  },
};